---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: olm
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    semver: ">= v0.23.1"
    # tag: "v0.23.1"
  url: https://github.com/operator-framework/operator-lifecycle-manager.git
  ignore: |
    # exclude all
    /*
    # include chart
    !/deploy/chart/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: olm
  namespace: flux-system
spec:
  interval: 1m0s
  chart:
    spec:
      chart: ./deploy/chart/
      sourceRef:
        kind: GitRepository
        name: olm
        namespace: flux-system
      interval: 1m
      # reconcileStrategy: Revision
